# Generated by Django 3.1.2 on 2020-12-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201210_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Is_author',
        ),
    ]
